# Generated by Django 4.1 on 2023-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
