# Generated by Django 4.1 on 2023-08-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_estimate_shipping_charge_estimate_item_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='TCS',
            new_name='shipping_charge',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='TCS',
            new_name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sales_item',
            name='description',
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxamount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='discount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales_item',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='taxamount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
