# Generated by Django 4.1 on 2023-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20230706_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gstno',
        ),
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
