# Generated by Django 4.1 on 2023-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_company_gstno_company_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='shipping_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote1',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
